### ISSUE TITLE
Constant

### ISSUE THREAD

**Issue by VB10** [hakanglg/otodo#6]
https://github.com/hakanglg/otodo/blob/0f0fa5547c90520dda24d301e7a50742fff41e80/lib/features/tasks/model/task_model.dart#L4

Projede farkli typler olabilir ondan oturu hiveconstat icinde static const ile type imsi ata
misal TaskType = 1

**Comment by hakanglg** [comment]
![image](https://user-images.githubusercontent.com/58719777/167268668-16092abd-d5fb-4d10-aeca-a641a1a8cba0.png)
Teşekkürler hocam
